baseURL: 'https://codingqilin.com/'
languageCode: 'en-us'
title: 'Coding Qilin'
theme: ["hugo-video", "PaperMod"]

params:
  homeInfoParams:
    title: "Welcome to the Coding Qilin"
    content: "A new blog site under construction."
  socialIcons: 
      - name: "github"
        url: "https://github.com/BlenderSleuth"
      - name: "twitter"
        url: "https://twitter.com/Blendersleuth"
      - name: "discord"
        url: "https://discordapp.com/users/BlenderSleuth#9541"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/ben-sutherland-a9a8b21a5/"

  assets:
    favicon: "favicon/favicon.ico"
    favicon16x16:  "favicon/favicon-16x16.png"
    favicon32x32:  "favicon/favicon-32x32.png"
    apple_touch_icon:  "favicon/apple-touch-icon.png"
    disableHLJS: true

  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  comments: true

menu:
  main:
    - name: Search
      pageRef: /search
      pre: <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 28 20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="11" cy="11" r="8"></circle>
            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
        </svg>
      weight: 10

outputs:
  home:
      - HTML
      - JSON

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: false
    style: catppuccin-mocha

    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    noHl: false
    tabWidth: 4

module:
  mounts:
  - source: content
    target: content
  - excludeFiles: /**.psd
    source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes
